CLIENT_ENV: dev

rolle:
  veileder: "3611981f-eda7-46ab-b8f2-50c3159e101c"
  beslutter: "dab3f549-f5f0-4a9c-9f5b-1f6a15ae8424"
  saksbehandler: "31a99292-9461-40bf-b2d0-a815697dfbb4"
  kode6: "5ef775f2-61f8-4283-bf3d-8d03f428aa14" # 0000-GA-Strengt_Fortrolig_Adresse
  kode7: "ea930b6b-9397-44d9-b9e6-f4cf527a632a" # 0000-GA-Fortrolig_Adresse
  egenAnsatt: "dbe4ad45-320b-4e9a-aaa1-73cca4ee124d" # 0000-GA-Egne_ansatte
  prosessering: "928636f4-fd0d-4149-978e-a6fb68bb19de" # 0000-GA-STDAPPS gir alle tilgang i preprod til prosessering

TILLEGGSTONADER_BEHANDLING_TOPIC: tilleggstonader.aapen-tilleggsstonader-behandling-test


clients:
  pdl:
    uri: https://pdl-api-q1.${CLIENT_ENV}-fss-pub.nais.io
    scope: api://${CLIENT_ENV}-fss.pdl.pdl-api-q1/.default
  kodeverk:
    uri: https://kodeverk-api.nav.no
