rolle:
  veileder: "0f841c83-0d64-407c-80d5-4eb51dfaee1e"
  beslutter: "c1e9edec-0c10-4df2-8c74-324ab9922220"
  saksbehandler: "224b5097-d0af-462c-8d8e-49c0e8a42661"
  kode6: "5ef775f2-61f8-4283-bf3d-8d03f428aa14" # 0000-GA-Strengt_Fortrolig_Adresse
  kode7: "ea930b6b-9397-44d9-b9e6-f4cf527a632a" # 0000-GA-Fortrolig_Adresse
  egenAnsatt: "dbe4ad45-320b-4e9a-aaa1-73cca4ee124d" # 0000-GA-Egne_ansatte

CLIENT_ENV: dev